import { Commodity } from './types';

export const COMMODITIES: Commodity[] = [
  {
    id: 'fdst',
    ticker: 'FDST',
    name: 'Fractol Dust',
    lore: 'Crystalline prediction residue harvested from broken AI dreams.',
    basePrice: 450,
    volatility: 0.85,
    size: 2,
    heatRisk: 0.3,
    tags: ['prediction', 'volatile', 'crystal'],
    rarity: 'uncommon',
  },
  {
    id: 'pgas',
    ticker: 'PGAS',
    name: 'Plutonion Gas',
    lore: 'Sealed micro-reactor vapor used in illegal grid bursts.',
    basePrice: 1200,
    volatility: 0.55,
    size: 5,
    heatRisk: 0.5,
    tags: ['infrastructure', 'energy', 'reactor'],
    rarity: 'uncommon',
  },
  {
    id: 'ngls',
    ticker: 'NGLS',
    name: 'Neon Glass',
    lore: 'Optical memory shards that refract corrupted Pantheon fragments.',
    basePrice: 800,
    volatility: 0.45,
    size: 1,
    heatRisk: 0.2,
    tags: ['memory', 'archivist', 'lore'],
    rarity: 'uncommon',
  },
  {
    id: 'hxmd',
    ticker: 'HXMD',
    name: 'Helix Mud',
    lore: 'Bio-synthetic coolant sludge for overheated drone minds.',
    basePrice: 350,
    volatility: 0.6,
    size: 4,
    heatRisk: 0.25,
    tags: ['bio', 'coolant', 'drone'],
    rarity: 'common',
  },
  {
    id: 'vblm',
    ticker: 'VBLM',
    name: 'Void Bloom',
    lore: 'Fungal code growth that eats dead packets and sells as compute feed.',
    basePrice: 75,
    volatility: 0.3,
    size: 8,
    heatRisk: 0.1,
    tags: ['fungal', 'compute', 'bulk', 'beginner'],
    rarity: 'common',
  },
  {
    id: 'orrs',
    ticker: 'ORRS',
    name: 'Oracle Resin',
    lore: 'Predictive resin wafers used by market prophets.',
    basePrice: 2500,
    volatility: 0.7,
    size: 1,
    heatRisk: 0.4,
    tags: ['prediction', 'premium', 'news-sensitive'],
    rarity: 'rare',
  },
  {
    id: 'snps',
    ticker: 'SNPS',
    name: 'Synapse Silk',
    lore: 'Threaded neural weave for stealth runners.',
    basePrice: 1800,
    volatility: 0.5,
    size: 2,
    heatRisk: 0.35,
    tags: ['stealth', 'neural', 'faction'],
    rarity: 'rare',
  },
  {
    id: 'mtrx',
    ticker: 'MTRX',
    name: 'Matrix Salt',
    lore: 'Rare lattice salt for decrypting old city relays.',
    basePrice: 3500,
    volatility: 0.4,
    size: 1,
    heatRisk: 0.45,
    tags: ['decrypt', 'rare', 'node'],
    rarity: 'legendary',
  },
  {
    id: 'aeth',
    ticker: 'AETH',
    name: 'Aether Tabs',
    lore: 'Temporary perception patches for Eidolon routing models.',
    basePrice: 200,
    volatility: 0.9,
    size: 1,
    heatRisk: 0.15,
    tags: ['perception', 'cheap', 'speculative'],
    rarity: 'common',
  },
  {
    id: 'blck',
    ticker: 'BLCK',
    name: 'Blacklight Serum',
    lore: 'Synthetic signal dye for hiding ghost packets.',
    basePrice: 5000,
    volatility: 0.75,
    size: 1,
    heatRisk: 0.8,
    tags: ['stealth', 'premium', 'high-heat'],
    rarity: 'legendary',
  },
];

export const COMMODITY_MAP = Object.fromEntries(
  COMMODITIES.map((c) => [c.id, c])
);

export function getCommodity(id: string): Commodity {
  const c = COMMODITY_MAP[id];
  if (!c) throw new Error(`Unknown commodity: ${id}`);
  return c;
}
